/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'kazuhito_m' at '15/03/29 2:44' with Gradle 2.3
 *
 * @author kazuhito_m, @date 15/03/29 2:44
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
