/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'kazuhito_m' at '15/03/29 2:44' with Gradle 2.3
 *
 * @author kazuhito_m, @date 15/03/29 2:44
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
